name: Docker CD

on:
  release:
    tags:
      - v*
    types: [published]

jobs:
  publish-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Client - build and publish image
      run: |
        pushd ./Client
        docker build -t docker.pkg.github.com/${{ github.repository }}/client:$(echo ${{ github.ref }} | sed 's/refs\/tags\///g') .
        docker tag docker.pkg.github.com/${{ github.repository }}/client:$(echo ${{ github.ref }} | sed 's/refs\/tags\///g') docker.pkg.github.com/${{ github.repository }}/client:latest
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin
        docker push docker.pkg.github.com/${{ github.repository }}/client:$(echo ${{ github.ref }} | sed 's/refs\/tags\///g')
        docker push docker.pkg.github.com/${{ github.repository }}/client:latest
  publish-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Server - build and publish image
      run: |
        pushd ./Server
        docker build -t docker.pkg.github.com/${{ github.repository }}/server:$(echo ${{ github.ref }} | sed 's/refs\/tags\///g') .
        docker tag docker.pkg.github.com/${{ github.repository }}/server:$(echo ${{ github.ref }} | sed 's/refs\/tags\///g') docker.pkg.github.com/${{ github.repository }}/server:latest
        echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ github.actor }} --password-stdin
        docker push docker.pkg.github.com/${{ github.repository }}/server:$(echo ${{ github.ref }} | sed 's/refs\/tags\///g')
        docker push docker.pkg.github.com/${{ github.repository }}/server:latest
  trigger-webhooks:
    runs-on: ubuntu-latest
    needs: publish-server
    steps:
    - name: Trigger Webhooks
      run: |
        curl -X POST -d -H '${{ secrets.SERVER_WEBHOOK }}' > /dev/null
